[project]
name = "streamlit-langgraph-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "azure-devops>=7.1.0b4",
    "duckduckgo-search>=8.1.1",
    "fastapi>=0.116.1",
    "grpcio>=1.74.0",
    "httpx>=0.28.1",
    "jiter>=0.10.0",
    "langchain-anthropic>=0.3.19",
    "langchain-aws>=0.2.31",
    "langchain-community>=0.3.27",
    "langchain-core>=0.3.74",
    "langchain-google-genai>=2.1.9",
    "langchain-groq>=0.3.7",
    "langchain-ollama>=0.3.7",
    "langchain-openai>=0.3.31",
    "langgraph>=0.6.6",
    "langgraph-checkpoint-postgres>=2.0.23",
    "langgraph-checkpoint-sqlite>=2.0.11",
    "langgraph-supervisor>=0.0.29",
    "langsmith>=0.4.16",
    "numexpr>=2.11.0",
    "numpy>=2.3.2",
    "pandas>=2.3.2",
    "psycopg[binary,pool]>=3.2.9",
    "pyarrow>=21.0.0",
    "pydantic>=2.11.7",
    "pydantic-settings>=2.10.1",
    "pyowm>=3.4.0",
    "python-dotenv>=1.1.1",
    "setuptools>=80.9.0",
    "streamlit>=1.48.1",
    "tiktoken>=0.11.0",
    "uvicorn>=0.35.0",
]
